#!/usr/bin/env node
/**
 * build-env.js — reads .env and writes claude_ui/env-config.js
 *
 * Run once before starting the dev server:
 *   node build-env.js
 *
 * claude_ui/env-config.js is gitignored; never commit it.
 * It sets window.__AM_ENV so supabase_client.js can read credentials.
 */
const fs   = require('fs');
const path = require('path');

const envPath    = path.join(__dirname, '.env');
const outPath    = path.join(__dirname, 'claude_ui', 'env-config.js');

if (!fs.existsSync(envPath)) {
  console.error('ERROR: .env not found at', envPath);
  console.error('Create it with SUPABASE_URL= and SUPABASE_ANON_KEY= values.');
  process.exit(1);
}

const env = {};
fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) return;
  const eq = trimmed.indexOf('=');
  if (eq === -1) return;
  const key = trimmed.slice(0, eq).trim();
  const val = trimmed.slice(eq + 1).trim();
  env[key] = val;
});

const url  = env.SUPABASE_URL     || '';
const anon = env.SUPABASE_ANON_KEY || '';

if (!url || !anon) {
  console.warn('WARNING: SUPABASE_URL or SUPABASE_ANON_KEY is empty in .env');
  console.warn('Fill in the values then re-run: node build-env.js');
}

const out = `// AUTO-GENERATED by build-env.js — do not edit or commit
window.__AM_ENV = ${JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: anon }, null, 2)};
`;

fs.writeFileSync(outPath, out, 'utf8');
console.log('✓ Wrote', outPath);
if (url) console.log('  SUPABASE_URL =', url);
if (anon) console.log('  SUPABASE_ANON_KEY =', anon.slice(0, 8) + '…');
